def funWithAnagrams(text)
  i = 1
  (text.size).times {
    if i + 1 > text.size
      break
    else
      (0..(i-1)).each { |n|
        text_i = text[i].split("").sort
        text_n = text[n].split("").sort
        if  text_n == text_i
          text.delete_at(i)
          i -= 1
          break
        end
      }
    end
    i += 1
  }
  text.sort
  puts text.size
end


# TEST

text_a = ["code","aaagmnrs","anagrams","doce"]
puts "STRINGS A:"
funWithAnagrams(text_a)
# Output: ["aaagmnrs", "code"]

text_b = ["poke","pkoe","okpe","ekop"]
puts "STRINGS B:"
funWithAnagrams(text_b)
# Output: ["poke"]

text_c = %w(code doce ecod framer frame)
puts "STRINGS C:"
funWithAnagrams(text_c)
# Output: ["code", "frame", "framer"]

text_d = %w(
  aaa
  bbb
  ccc
)
puts "STRINGS D:"
funWithAnagrams(text_d)
# Output: ["aaa", "bbb", "ccc"]

text_e = %w(
  fqwltvzkqt
  volphckcyufdqmlglimklfzktgygdttnhcvpfdfbrp
  lkvshwywshtdgmbqbkkxcvgumo
  mwvytbytnuqhmfjaqtgngcwkuzyamnerphfmwevh
  lezohyeehbrcewjxvceziftiqtntfsrptugtiznorvonzjfea
  gamayapwlmbzitzszhzkosvnknber
  ltlkggdgpljfisyltmmfvhybljvk
  pcflsaqevcijcyrgmqirzniax
  kholawoydvchveigttxwpukzjfh
  brtspfttotafsngqvoijxuvq
  ztvaalsehzxbshnrvbykjqlrzzfm
  vyoshiktodnsjjpqplciklzqrxloqxrudygjty
  leizmeainxslwhhjwslqendjvx
  yghrveuvphknqtsdtwxcktmwwwsdthzmlmbh
  kmouhpbqur
  fxgqlojmwsomowsjvpvhznbsilhhdkbdxqgrgedpzch
  gefeukmcowoeznwhpiiduxdnnlbnmyjyssbsococdzcu
  nkrfduvouaghhcyvmlkza
  jpfpyljtyjjpyntsefxiswjuten
  ycpbcnmhfuqmmidmvknyxmywegmtunodvuzygvguxtrdsdf
  fssmeluodjgdgzfmrazvndtaur
  kugs
  dpawxitivdubbqeonycaegxfjkkl
  fkraoheucsvpiteqrs
  gkaaaohxxzhqjtkqaqhkwbe
  bpmglbjipnujywogwc
  lkyrdejaqufowbigrsnjniegvd
  otugocedktcbbufnxorixibbdfrzuqsyrfqghoyqevcuanuu
  szitaoaowsxyglafbwzddoznrvjqeyqignpi
  ruijvyllsibobjltusrypanvybsfrxtlfmpdidtyozoolz
  lgdgowijatklvjzscizrkupmsoxftumyxifyunxucubvk
  ctkqlr
  qgzjvjwzizppvso
  flvioemycnphf
  tbnwedtubynsbirepgcxfgsfomhvpmymkdoh
  ttyyc
  ibbeaxniwjkfvabnrll
  maglythkgla
  zgkeulyrpaeurdvexqlwgakdtbihmfrjijanxkhrqdllecy
  pcflsaqevcijcyrgmqixnzira
  klqrct
  ibbeaxniwjkfvanrbll
  vyoshiktodnsjjpqplciklzqrxloqxrudyyjtg
  ycpbcnmhfuqmmidmvknyxmywegmtunodvuzygvgxddftsru
  yyctt
  yghrveuvphknqtsdtwxcktmwwwsdtlhbhmmz
  vyoshiktodnsjjpqplciklzqrxloqxrugyytjd
  cttyy
  brtspfttotafsngqvoiqxuvj
  lkyrdejaqufowbigrsnjvedgin
  volphckcyufdqmlglimklfzktgygdttnhcvpfdrbpf
  qgzjvjwzizpsovp
)
puts "STRINGS E:"
funWithAnagrams(text_e)

text_f = %w(
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidajwlkf
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypstsxhp
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivarjdk
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumnwehj
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljgzyvem
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvnvtnqs
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptpsxsh
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhjewm
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypsxpsth
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypsxthsp
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjhmew
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivkardj
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljgzyvme
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqnnvts
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawljkf
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhmwej
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidfaljkw
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawjkfl
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjwemh
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypxhstps
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmygvze
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqntnvs
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqstnvn
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypxhstps
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidaklwjf
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqnstvn
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwhjne
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypsxsthp
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvsnnqtv
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmyzveg
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidfajwlk
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhmwje
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmgzeyv
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidfajwkl
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivkajdr
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqnntsv
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwejhn
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunewmhj
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwenjh
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawjlkf
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidakjlwf
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidakjlwf
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqvsnnt
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypsxshpt
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmegzvy
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypsxhpst
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwnehj
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvsqntvn
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivdkajr
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidfakljw
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptxpssh
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmegvzy
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwjneh
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjmwhe
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptxphss
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawjkfl
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmvgeyz
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypstsxph
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypsxhspt
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivrkajd
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmyvzge
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjemwh
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypsxshpt
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivdjrka
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmezygv
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptspshx
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjmwhe
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvsqntvn
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmegyzv
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvsntnqv
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunehjmw
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjhmwe
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidfajkwl
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivkradj
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwenjh
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawkjlf
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidfalkwj
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhjmew
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmeyvgz
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhwmje
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivradkj
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptxsshp
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawfkjl
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypsxshtp
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunejwhm
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivradkj
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidakfwjl
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvsnvnqt
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhwjme
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypthsxps
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjwhme
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmyegvz
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivkjdar
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivdrajk
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhjemw
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmgzvye
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqnsvtn
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptspsxh
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidfajkwl
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivrjadk
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqvntns
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivdjakr
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqnnvst
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqrypxhpsst
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidalwkjf
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmvegyz
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqntnvs
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunehmjw
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivrjkda
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidakjwfl
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptshspx
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvqtvsnn
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawkjlf
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumnwhej
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawljfk
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwhjen
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjmwhe
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmvyzge
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhmewj
  spwvpfyfpkvgthqqrmajxispjncxgviyuqavayvsvznmhskodmidawfljk
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivrdakj
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivkjrad
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljgzyvem
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivjdkra
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptsspxh
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivdkarj
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhewjm
  hnlcrldtfthulkxhflcoupgeikrlaksuyfqvsnvtnq
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhwemj
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwjhen
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivrjkda
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmyvgze
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumwnjeh
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunjwhem
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptpssxh
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmgzvey
  imprrhenguipdghstyopbvuiqcoplvwduwmjpblqoafnxwgqtvwztjekxwnbcuggliiehimvoymyjasinwspsqiukflhyfacamqrbqryptspsxh
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmevyzg
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmgyzve
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivdajkr
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvunhemwj
  oswnprlhvsuzvgyeettenngipfvrflpprjjalchhhcmhxkupciulccqssaqgdttpldmzdzveslyjadswtsbhgkddeouxbldsxzmfvhtonlampljmgzvey
  fcfpotnvlcibpxkidmwexpugwoxjicdkvstltienwqngiutnuqbzicontzlybgvumnwhje
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivdrkja
  rrmbeddvphnegtuxxtalsyxezjwtlwmxvrjtxytykkckuvbhhlovgcxjxhhivxnutkxvhadiaysulvknmcanhsyxlivjrkda
)
puts "STRINGS F:"
funWithAnagrams(text_f)
